# =============================================================================
# Docker Compose - Simple Setup (Educational/Quick Start)
# =============================================================================
# This is a minimal Docker Compose configuration for students and learning.
# Perfect for educational use with public Google Sheets and console logging.
#
# Usage:
#   1. cp .env.example .env
#   2. Edit .env and set GOOGLE_SHEET_ID (make sheet public first!)
#   3. docker-compose -f docker-compose.simple.yml up -d
#
# Features:
#   - No credential files needed
#   - Works with public Google Sheets
#   - Notifications to console logs
#   - Minimal configuration
# =============================================================================

version: '3.8'

services:
  btc-trading-bot:
    build: .
    container_name: btc-trading-bot-simple
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Application settings
      - DEBUG=${DEBUG:-false}
      - HOST=0.0.0.0
      - PORT=8000

      # Google Sheets configuration (public sheet only)
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_WORKSHEET_NAME=${GOOGLE_WORKSHEET_NAME:-Sheet1}

      # No credentials needed for public sheets!
      # Notifications default to console logs (no setup required)

      # Optional: Coinbase configuration
      - COINBASE_CANDLES_GRANULARITY=${COINBASE_CANDLES_GRANULARITY:-30m}

      # File paths
      - CONFIG_CACHE_PATH=/app/data/cache/config_cache.json
    volumes:
      # Data persistence
      - ./data:/app/data

      # Configuration file
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - btc-bot-network

networks:
  btc-bot-network:
    driver: bridge

volumes:
  data:
    driver: local
